# Workflow for deploying contents of Sosaku for web to GitHub Pages
name: Sosaku for Web

on:
  # Triggered from Codemagic workflow or contributors.
  repository_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
#      - name: Repository
#        id: version
#        run: |
#          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
#          echo ::set-output name=repository::$REPOSITORY
      - name: Install Flutter latest environment
        uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.3.4'
          channel: 'stable'
          cache: true
      - name: Pre-build process
        - run: |
            flutter doctor -v
            flutter pub get
            flutter gen-l10n
            flutter pub run icons_launcher:create
            flutter pub run flutter_native_splash:create
      - name: Build Sosaku for Web
        # If you use default URL (do not use custom domain), --base-href option is required.
        - run: flutter build web --release --build-number=${{ github.event.client_payload.build_number }} --web-renderer canvaskit #--base-href /${{ steps.version.outputs.repository }}/
      - name: Upload artifacts to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/web'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      # Define Discord description
      - run: |
          if [ "${job.status}" == "success" ]; then
            echo "description=Please try the latest build [here](https://w-sharp-tcu.github.io/sosaku/)!" >> $GITHUB_ENV
          else
            echo "description=Please check the details of the latest build results [here](https://github.com/W-sharp-TCU/sosaku/deployments/activity_log?environment=github-pages)." >> $GITHUB_ENV
          fi
      # Notify Discord Channel
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub Actions
          nocontext: true
          title: "deploy to GitHub Pages"
          description: ${{ env.description }}
