name: Enumerate asset file paths

on:
  push:
    branches:
      - feature/create_StringParser

jobs:
  build:
    name: Upload assets file paths to Google Sheets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: .github/workflows/python_requirements.txt
      - name: Show Python version
        run: python -V
      - name: Install dependencies
        run: python -m pip install -r .github/workflows/python_requirements.txt
      - name: Run python script
        env:
          # Set Repository secrets to environment variable
          CREDENTIAL_JSON: ${{ secrets.CREDENTIAL_JSON }}
          SPREADSHEET_KEY: ${{ secrets.SPREADSHEET_KEY }}
        run: python .github/workflows/enumerate_assets.py